### ISSUE TITLE
Default to `BasicProjector` if `fast_jl` import fails

### ISSUE THREAD

**Issue by kristian-georgiev** [MadryLab/trak#21]

**Comment by kristian-georgiev** [comment]
https://github.com/MadryLab/trak/commit/9926ac1e9577d0d23174800f049d336ede1a0efe @jvendrow wdyt

**Comment by jvendrow** [comment]
Looks good. Added another error (AttributeError) that appears for me in an environment where fast_jl is installed incorrectly.

**Comment by kristian-georgiev** [comment]
https://github.com/MadryLab/trak/commit/9d6cd79dff08d2ddea9c81e70690f77988285f4f
