### ISSUE TITLE
FAILED tests/test_rademacher.py::test_odd - AssertionError: Expected <True>, but was not.

### ISSUE THREAD

**Issue by xszheng2020** [MadryLab/trak#23]
Hi, @kristian-georgiev thanks for your great work.

I installed traker by `pip install traker[fast]` under PyTorch 1.13.1
And then I tested `python -m pytest -sv tests/test_rademacher.py`
It shows 
```
FAILED tests/test_rademacher.py::test_odd - AssertionError: Expected <True>, but was not.
1 failed, 14 passed, 4 warnings in 3.10s
```
Any idea?

**Comment by kristian-georgiev** [comment]
I think this issue has the same root cause as https://github.com/MadryLab/trak/issues/24, addressing it there.
