### ISSUE TITLE
Gradient_Computers grad.dtype shouldn't inherit from batch[0].dtype?

### ISSUE THREAD

**Issue by awe2** [MadryLab/trak#44]
in lines 105-107 of [trak/gradient_computers.py](trak/gradient_computers.pyhttps://github.com/MadryLab/trak/blob/2b0dd496e7aaaf1f951fd57581d630189f3724e2/trak/gradient_computers.py#L105C1-L107C52)

```python 
 grads = torch.empty(size=(batch[0].shape[0], self.num_params),
                      dtype=batch[0].dtype,
                      device=batch[0].device)
```
grads tensor inherits from the dtype of tensor in batch[0], but fast_jl.cu asserts that the dtype of grads is torch.float32 or torch.float16. If batch[0] is not dtype torch.float32 or torch.float16 then CudaProjector fails. (e.g., Input to language model might be tokenized words with dtype torch.uint32)

Possible solution: should grads.dtype inherit the dtype from the user specified dtype in TRAKer.use_half_precision instead?

**Comment by kristian-georgiev** [comment]
Hi @awe2, good catch! I think your solution should work :) Do you want to submit a PR?

**Comment by kristian-georgiev** [comment]
Addressed in https://github.com/MadryLab/trak/commit/fb5e0a495a859359b382b6b2a066800f5f7f66c7 (on branch https://github.com/MadryLab/trak/tree/0.2.2 for now, will be merged in main in the next release)
