### ISSUE TITLE
How to implement get_output() function for segmentation task?

### ISSUE THREAD

**Issue by yangchaohua** [MadryLab/trak#47]
Hi!
    Thank you for sharing this work. 
    I want to use TRAK for my segmentation task (each pixel of the model is represented as a binary classification of whether it is a foreground or not), I don't know which method is more suitable for calculating f(z; θ), sum of the output or average of the output. Is there any other better method?

**Comment by kristian-georgiev** [comment]
Hi @yangchaohua. We haven't ran experiments with segmentation models. Based on our [preliminary work](https://openreview.net/pdf?id=9hK9NbUAex) with diffusion models (where the output is also high-dimensional), my guess is that the sum of per-pixel outputs should be a good start.
