### ISSUE TITLE
RuntimeError: CUDA error: the provided PTX was compiled with an unsupported toolchain.

### ISSUE THREAD

**Issue by simplelifetime** [MadryLab/trak#68]
What might be the caused of this problem, example code:
import fast_jl

fast_jl.project_rademacher_8(torch.zeros(
8, 1_000, device=device), 512, 0, num_sms)

cuda version: Cuda compilation tools, release 11.8, V11.8.89

nvidia driver: 460.91.03

**Comment by kristian-georgiev** [comment]
This is likely due to a mismatch between your nvidia driver and cuda toolkit version, and not related to TRAK. I would start from the NVIDIA docs: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#running-the-binaries.

**Comment by simplelifetime** [comment]
Thanks, updating driver to 530.35 and cuda version to 12.1 solve the problem

**Comment by shangqing-liu** [comment]
@simplelifetime Hi I also met this problem  which the exact driver version can you provide to solve this problem. Thanks.
