### ISSUE TITLE
`CLIPModelOutput` gradient computation wrong dimensionality

### ISSUE THREAD

**Issue by dwahdany** [MadryLab/trak#73]
The function `CLIPModelOutput.get_out_to_loss_grad` outputs a `[batch_size]`-shaped tensor, but it should be (for consistency with other methods and compatibility with `saver.current_store["out_to_loss"]`) `[batch_size, 1]`-shaped. All other models have a `unsqueeze(-1)` at the end, for CLIP it seems to be missing.

**Comment by kristian-georgiev** [comment]
resolved by https://github.com/MadryLab/trak/pull/72; thanks @dwahdany!
